# site settings
title: Stamp Demo
subtitle: by Eigenplanet
email: gilang@eigenplanet.com
description: Start page for Stamp demo
baseurl: "/stamp-demo" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Eigenplanet

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
200px_url:
facebook_url:
github_url:
pinterest_url:
slack_url:

# build settings
markdown: kramdown

sass:
  style: compressed
